project_id = "lrricdforqfkaaciammv"

[functions.generate-book]
verify_jwt = false

[functions.generate-chapter]
verify_jwt = false

[functions.generate-cover]
verify_jwt = false

[functions.content-filter]
verify_jwt = false

[functions.export-book]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.claim-admin]
verify_jwt = false
