// Content quality cleanup and AI-artifact auditing for export-bound chapters.
//
// What this module is for
// -----------------------
// Chapter content is generated by an LLM and stored verbatim. The raw text
// routinely contains four classes of issues that are invisible inside the
// in-app reader (which renders forgiving markdown) but lethal once a buyer
// opens the file on a Kindle / Gumroad / Etsy download:
//
//   1. AI preambles/postambles — "Sure! Here is the chapter:", "I hope this
//      helps! Let me know if you'd like…" These are obvious to any reader
//      and instantly mark the book as AI-generated.
//   2. AI self-references — "as an AI", "as a language model", "I cannot
//      provide". Worse than preambles because they break the fictional voice
//      mid-chapter and trip Amazon's content-moderation filters.
//   3. Bracketed placeholders — "[TBD]", "[INSERT EXAMPLE HERE]", "[Note to
//      editor: rephrase]". Caused by partial generations or interrupted
//      streams. Buyers see them. Customer-service problem.
//   4. Structural / typographic noise — unclosed code fences, mixed line
//      endings, zero-width chars, double-hyphen instead of em-dash, ASCII
//      "..." instead of "…", stray `<script>` from copy-pasted HTML. The
//      reader hides these; EPUB/PDF do not.
//
// Contract
// --------
// `cleanChapterContent(raw)` returns a deterministic, byte-for-byte stable
// rewrite. Anything that can be safely auto-fixed IS fixed (preambles,
// fences, line endings, typography, dangerous HTML). Anything that requires
// human judgement is left alone and reported via `auditChapterArtifacts`.
//
// All exports are pure. Same inputs ⇒ same outputs. No I/O.

export type ContentIssueSeverity = "blocker" | "warning" | "info";

export interface ContentIssue {
  severity: ContentIssueSeverity;
  code: string;
  message: string;
  /** When attributable to a specific chapter. */
  chapter?: number;
  /** Short hint for the creator (≤160 chars). */
  hint?: string;
}

export interface ContentCleanupStats {
  preambles_stripped: number;
  postambles_stripped: number;
  placeholders_found: number;
  ai_self_references_found: number;
  unclosed_code_fences_closed: number;
  empty_headings_removed: number;
  dangerous_html_stripped: number;
  smart_typography_applied: number;
  zero_width_chars_removed: number;
  /** Whether anything at all changed. */
  changed: boolean;
}

export const EMPTY_STATS: ContentCleanupStats = {
  preambles_stripped: 0,
  postambles_stripped: 0,
  placeholders_found: 0,
  ai_self_references_found: 0,
  unclosed_code_fences_closed: 0,
  empty_headings_removed: 0,
  dangerous_html_stripped: 0,
  smart_typography_applied: 0,
  zero_width_chars_removed: 0,
  changed: false,
};

// ─── Patterns ──────────────────────────────────────────────────────────────

// AI preamble: a chatty line at the very start of the chapter announcing
// that what follows is the chapter. Anchored to the first paragraph only —
// we never strip something deep in the body.
const PREAMBLE_RE = new RegExp(
  "^\\s*(?:" +
    // openers
    "(?:Sure|Certainly|Absolutely|Of course|Great|Awesome|Alright)[!,.]?\\s*" +
    "|(?:Here(?:'|’)s|Here you go|Below(?:\\s+is)?|This is)\\s+" +
    "|(?:I(?:'|’)?d be happy to|I(?:'|’)?ll|I will|Let me)\\s+(?:write|help|share|provide|give|craft|compose)\\s+" +
    "|As (?:requested|you asked)[,.]?\\s*" +
    "|Below(?:\\s+is)?\\s+(?:the\\s+)?(?:next\\s+)?chapter" +
  ")" +
  // up to the end of the first paragraph
  "[^\\n]*\\n\\n",
  "i",
);

// AI postamble: a chatty line at the very end inviting follow-up.
const POSTAMBLE_RE = new RegExp(
  "(?:\\n\\n|^)\\s*(?:" +
    "(?:Let me know|Feel free to|If you(?:'|’)d like|I hope (?:this|that)|Would you like me|Hope (?:this|that))\\b[^\\n]*" +
    "|(?:That(?:'|’)s|This)\\s+(?:concludes|wraps up|ends|completes|finishes)\\b[^\\n]*" +
    "|\\[(?:Note|Editorial|Author|End of chapter)[^\\]]*\\]" +
    "|---?\\s*(?:Continued|To be continued)\\b[^\\n]*" +
  ")\\s*$",
  "i",
);

// AI self-reference patterns. We FLAG these (warning) rather than auto-strip
// because some books legitimately contain them (e.g. an AI-themed thriller).
const SELF_REFERENCE_PATTERNS: Array<{ code: string; re: RegExp; message: string }> = [
  { code: "ai_self_reference",
    re: /\b(?:as an? AI|as a language model|I am an AI|I'm an AI|I am a language model|I'm a language model|as a large language model)\b/gi,
    message: "Chapter contains AI self-reference" },
  { code: "ai_refusal",
    re: /\b(?:I (?:cannot|can't|am unable to|won't)|I do not have the ability|I'm sorry,? (?:but )?I)\b[^.\n]{0,80}\b(?:assist|help|provide|generate|create|write|comply)\b/gi,
    message: "Chapter contains an AI refusal phrase" },
];

// Bracketed placeholders. STRIP "[" wrappers around clearly unfinished
// editorial markers; leave anything that looks like a legitimate aside.
const PLACEHOLDER_PATTERNS: Array<{ code: string; re: RegExp; replacement: string | null; message: string }> = [
  { code: "placeholder_tbd",   re: /\[\s*(?:TBD|TODO|FIXME|PENDING|PLACEHOLDER|WIP|XXX)\s*\]/gi,           replacement: "",     message: "Unresolved placeholder" },
  { code: "placeholder_insert", re: /\[\s*(?:INSERT|ADD|REPLACE|FILL IN|REWRITE)\b[^\]\n]*\]/gi,            replacement: "",     message: "Unfilled placeholder" },
  { code: "placeholder_note",  re: /\[\s*Note (?:to (?:self|editor|author|reader))?[:\s][^\]\n]*\]/gi,    replacement: "",     message: "Editorial note left in body" },
  { code: "placeholder_word_count", re: /\[\s*(?:Word count|Words?|Length)\s*:?\s*\d[^\]\n]*\]/gi,        replacement: "",     message: "Word-count marker left in body" },
];

// Dangerous HTML — strip with prejudice. We never preserve script/iframe/style
// tags or javascript: URIs.
const DANGEROUS_TAGS_RE = /<\s*(script|iframe|object|embed|style|link|meta)\b[\s\S]*?(?:<\s*\/\s*\1\s*>|$)/gi;
const ON_HANDLER_RE = /\son[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi;
const JAVASCRIPT_URI_RE = /\bhref\s*=\s*(?:"javascript:[^"]*"|'javascript:[^']*'|javascript:[^\s>]+)/gi;

// Zero-width characters: BOM, ZWSP, ZWNJ, ZWJ, WJ.
const ZERO_WIDTH_RE = /[﻿​‌‍⁠]/g;

// ─── Stage 1: byte-level normalisation ────────────────────────────────────

function normalizeLineEndings(s: string): string {
  return s.replace(/\r\n?/g, "\n");
}

function trimTrailingWhitespacePerLine(s: string): string {
  return s.split("\n").map((ln) => ln.replace(/[ \t]+$/g, "")).join("\n");
}

function collapseBlankRuns(s: string): string {
  // Three or more consecutive blank lines → one blank line break (two newlines).
  return s.replace(/\n{3,}/g, "\n\n");
}

// ─── Stage 2: AI artifact stripping ────────────────────────────────────────

function stripPreamble(s: string): { out: string; n: number } {
  const m = s.match(PREAMBLE_RE);
  if (!m) return { out: s, n: 0 };
  return { out: s.slice(m[0].length), n: 1 };
}
function stripPostamble(s: string): { out: string; n: number } {
  const m = s.match(POSTAMBLE_RE);
  if (!m) return { out: s, n: 0 };
  const idx = s.lastIndexOf(m[0]);
  if (idx < 0) return { out: s, n: 0 };
  return { out: s.slice(0, idx).replace(/\s+$/, ""), n: 1 };
}
function stripPlaceholders(s: string): { out: string; n: number } {
  let out = s;
  let n = 0;
  for (const p of PLACEHOLDER_PATTERNS) {
    out = out.replace(p.re, (match) => {
      n += 1;
      return p.replacement ?? match;
    });
  }
  // Tidy up any double spaces left behind by stripped placeholders.
  out = out.replace(/[ \t]{2,}/g, " ").replace(/\n[ \t]+\n/g, "\n\n");
  return { out, n };
}
function countSelfReferences(s: string): number {
  let n = 0;
  for (const p of SELF_REFERENCE_PATTERNS) {
    const m = s.match(p.re);
    if (m) n += m.length;
  }
  return n;
}

// ─── Stage 3: HTML defense-in-depth ────────────────────────────────────────

function stripDangerousHtml(s: string): { out: string; n: number } {
  let n = 0;
  let out = s.replace(DANGEROUS_TAGS_RE, () => { n++; return ""; });
  out = out.replace(ON_HANDLER_RE, () => { n++; return ""; });
  out = out.replace(JAVASCRIPT_URI_RE, () => { n++; return "href=\"#\""; });
  return { out, n };
}

// ─── Stage 4: structural healing (code fences, empty headings, hierarchy) ─

function closeUnclosedFences(s: string): { out: string; n: number } {
  // Count opening ``` lines. If odd, append a closer.
  // A "fence" line starts at column 0 (or after whitespace) and is a ```.
  const fences = s.match(/^[ \t]*```/gm) || [];
  if (fences.length % 2 === 0) return { out: s, n: 0 };
  const closer = s.endsWith("\n") ? "```\n" : "\n```\n";
  return { out: s + closer, n: 1 };
}

function removeEmptyHeadings(s: string): { out: string; n: number } {
  // "### " followed by only whitespace then newline (or EOF).
  let n = 0;
  const out = s.replace(/^[ \t]*#{1,6}[ \t]*$/gm, () => { n++; return ""; });
  return { out: out.replace(/\n{3,}/g, "\n\n"), n };
}

/**
 * The bundle pipeline emits the chapter title as an H1 above the chapter
 * body. If the body itself starts with an H1, the EPUB ends up with two
 * `<h1>` per chapter which fails accessibility audits and breaks Kindle's
 * "Chapters" navigation. We demote a body-level H1 to H2 here.
 */
function demoteBodyH1(s: string): string {
  const lines = s.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const t = lines[i].trimStart();
    if (!t) continue;
    if (t.startsWith("#")) {
      const m = t.match(/^(#+)\s/);
      if (m && m[1].length === 1) {
        const idx = lines[i].indexOf("#");
        lines[i] = lines[i].slice(0, idx) + "##" + lines[i].slice(idx + 1);
      }
    }
    // Only consider the first non-blank line.
    break;
  }
  return lines.join("\n");
}

// ─── Stage 5: typographic polish ───────────────────────────────────────────

function applySmartTypography(s: string): { out: string; n: number } {
  let n = 0;
  let out = s;

  // Don't touch the inside of code blocks. Easiest is to operate line by line
  // and skip when we're inside a fenced block.
  const lines = out.split("\n");
  let inFence = false;
  for (let i = 0; i < lines.length; i++) {
    if (/^[ \t]*```/.test(lines[i])) { inFence = !inFence; continue; }
    if (inFence) continue;
    let line = lines[i];
    const before = line;
    // ASCII ellipsis → typographic.
    line = line.replace(/\.{3,}/g, "…");
    // Double-hyphen between word-ish chars → em-dash (no surrounding spaces).
    line = line.replace(/(\w)\s*--\s*(\w)/g, "$1—$2");
    // Triple-hyphen as a sentence pause → em-dash.
    line = line.replace(/(\w)\s*---\s*(\w)/g, "$1—$2");
    // Number-en-dash-number range "1990-2020" → en-dash.
    line = line.replace(/(\d)\s*-\s*(\d{2,4}(?!\d))/g, "$1–$2");
    if (line !== before) n++;
    lines[i] = line;
  }
  out = lines.join("\n");
  return { out, n };
}

function removeZeroWidth(s: string): { out: string; n: number } {
  const matches = s.match(ZERO_WIDTH_RE);
  if (!matches) return { out: s, n: 0 };
  return { out: s.replace(ZERO_WIDTH_RE, ""), n: matches.length };
}

// ─── Public surface ────────────────────────────────────────────────────────

/**
 * Clean a single chapter's content for export. Returns the cleaned text plus
 * the cleanup stats so downstream code (the bundle manifest, the publishing
 * audit log) can record exactly what was changed.
 *
 * Idempotent: cleaning an already-cleaned chapter is a no-op (stats.changed
 * will be false).
 */
export function cleanChapterContent(raw: string | null | undefined): { cleaned: string; stats: ContentCleanupStats } {
  const stats: ContentCleanupStats = { ...EMPTY_STATS };
  if (!raw || typeof raw !== "string") return { cleaned: "", stats };

  let s = normalizeLineEndings(raw);
  const zw = removeZeroWidth(s);
  s = zw.out; stats.zero_width_chars_removed = zw.n;

  s = trimTrailingWhitespacePerLine(s);

  const pre = stripPreamble(s);
  s = pre.out; stats.preambles_stripped = pre.n;

  const post = stripPostamble(s);
  s = post.out; stats.postambles_stripped = post.n;

  const ph = stripPlaceholders(s);
  s = ph.out; stats.placeholders_found = ph.n;

  stats.ai_self_references_found = countSelfReferences(s);

  const html = stripDangerousHtml(s);
  s = html.out; stats.dangerous_html_stripped = html.n;

  const fences = closeUnclosedFences(s);
  s = fences.out; stats.unclosed_code_fences_closed = fences.n;

  const heads = removeEmptyHeadings(s);
  s = heads.out; stats.empty_headings_removed = heads.n;

  s = demoteBodyH1(s);

  const typo = applySmartTypography(s);
  s = typo.out; stats.smart_typography_applied = typo.n;

  s = collapseBlankRuns(s).trim();

  stats.changed = s !== raw;
  return { cleaned: s, stats };
}

export interface BookCleanupReport {
  totals: ContentCleanupStats;
  per_chapter: Array<{ chapter_number: number; stats: ContentCleanupStats }>;
  issues: ContentIssue[];
}

/**
 * Run cleanChapterContent over every chapter, accumulate stats, and produce
 * an audit-style issue list for anything that requires human judgement
 * (self-references, refusals — these never auto-strip).
 */
export function cleanBookChapters(
  chapters: Array<{ chapter_number: number; title: string | null; content: string | null }>,
): { cleaned: Array<{ chapter_number: number; title: string | null; content: string }>; report: BookCleanupReport } {
  const cleaned: Array<{ chapter_number: number; title: string | null; content: string }> = [];
  const perChapter: BookCleanupReport["per_chapter"] = [];
  const issues: ContentIssue[] = [];
  const totals: ContentCleanupStats = { ...EMPTY_STATS };

  for (const ch of chapters) {
    const { cleaned: text, stats } = cleanChapterContent(ch.content);
    cleaned.push({ chapter_number: ch.chapter_number, title: ch.title, content: text });
    perChapter.push({ chapter_number: ch.chapter_number, stats });

    for (const k of Object.keys(totals) as Array<keyof ContentCleanupStats>) {
      if (k === "changed") continue;
      (totals as any)[k] += (stats as any)[k];
    }

    if (stats.ai_self_references_found > 0) {
      issues.push({
        severity: "warning",
        code: "ai_self_reference",
        chapter: ch.chapter_number,
        message: `Chapter ${ch.chapter_number} contains ${stats.ai_self_references_found} AI self-reference${stats.ai_self_references_found === 1 ? "" : "s"} ("as an AI", "I cannot…")`,
        hint: "Rewrite these lines — Amazon's content moderation flags AI self-references on KDP submissions.",
      });
    }
  }
  totals.changed = totals.preambles_stripped + totals.postambles_stripped +
    totals.placeholders_found + totals.unclosed_code_fences_closed +
    totals.empty_headings_removed + totals.dangerous_html_stripped +
    totals.smart_typography_applied + totals.zero_width_chars_removed > 0;

  return { cleaned, report: { totals, per_chapter: perChapter, issues } };
}

/**
 * Audit-only variant for places that don't want to mutate content — e.g. the
 * `auditBookForExport` UI panel that surfaces issues to the creator before
 * they ever click "Publish externally".
 */
export function auditChapterArtifacts(content: string | null | undefined, chapterNumber?: number): ContentIssue[] {
  const issues: ContentIssue[] = [];
  if (!content) return issues;
  const s = normalizeLineEndings(content);

  if (PREAMBLE_RE.test(s)) {
    issues.push({ severity: "warning", code: "ai_preamble", chapter: chapterNumber,
      message: `Chapter ${chapterNumber ?? ""} starts with an AI-style preamble`,
      hint: 'Strip lines like "Sure! Here is the chapter:" before publishing.' });
  }
  if (POSTAMBLE_RE.test(s)) {
    issues.push({ severity: "warning", code: "ai_postamble", chapter: chapterNumber,
      message: `Chapter ${chapterNumber ?? ""} ends with an AI-style postamble`,
      hint: 'Remove sign-offs like "Let me know if you\'d like me to expand…".' });
  }
  for (const p of PLACEHOLDER_PATTERNS) {
    if (p.re.test(s)) {
      issues.push({ severity: "blocker", code: p.code, chapter: chapterNumber,
        message: `Chapter ${chapterNumber ?? ""}: ${p.message}`,
        hint: "Resolve all bracketed placeholders before publishing." });
      // PLACEHOLDER_PATTERNS regexes are flag/g so calling .test mutates lastIndex.
      p.re.lastIndex = 0;
    }
  }
  for (const p of SELF_REFERENCE_PATTERNS) {
    if (p.re.test(s)) {
      issues.push({ severity: "warning", code: p.code, chapter: chapterNumber,
        message: `Chapter ${chapterNumber ?? ""}: ${p.message}`,
        hint: "Amazon flags AI self-references; rewrite in the book's voice." });
      p.re.lastIndex = 0;
    }
  }
  if (DANGEROUS_TAGS_RE.test(s) || ON_HANDLER_RE.test(s)) {
    issues.push({ severity: "blocker", code: "dangerous_html", chapter: chapterNumber,
      message: `Chapter ${chapterNumber ?? ""} contains script/style tags or event handlers`,
      hint: "Remove inline HTML — it won't render and triggers KDP rejection." });
    DANGEROUS_TAGS_RE.lastIndex = 0;
    ON_HANDLER_RE.lastIndex = 0;
  }
  const fences = (s.match(/^[ \t]*```/gm) || []).length;
  if (fences % 2 !== 0) {
    issues.push({ severity: "warning", code: "unclosed_code_fence", chapter: chapterNumber,
      message: `Chapter ${chapterNumber ?? ""} has an unclosed code fence`,
      hint: "Add a closing ``` — the bundle pipeline auto-fixes this but reader rendering will look wrong." });
  }
  return issues;
}
