import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface SlideData {
  type: string;
  heading: string;
  content: string[];
  sourceReference?: string;
}

interface DeckGenerationParams {
  scope: 'chapter' | 'book';
  chapterNumbers?: number[];
  targetAudience: string;
  tone: string;
  maxSlides: number;
  includeVisuals: boolean;
  certificationContext: {
    bookId: string;
    bookVersion: string;
    contentHash: string;
  };
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { bookId, params, bookTitle } = await req.json() as {
      bookId: string;
      params: DeckGenerationParams;
      bookTitle: string;
    };

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    // Build system prompt based on VLD-1.0 contract
    const systemPrompt = `You are a Verified Learning Deck generator for ScrollLibrary.

You create structured presentation slides from educational book content following strict rules:

## SLIDE STRUCTURE (MANDATORY)
1. Title Slide: Book title, chapters covered, "Verified Learning Deck", version
2. Learning Objectives: 3-5 clear objectives extracted from content
3. Core Concept Slides: One concept per slide, 3-5 bullet points max, plain language
4. Application/Example Slide: Real-world example or use case
5. Summary Slide: Key takeaways + verification badge

## RULES
- Every concept slide MUST include "Source: Chapter X, Section Y"
- NO summarizing content not in the book
- NO AI hallucinations or made-up examples
- Maximum ${params.maxSlides} slides
- Tone: ${params.tone}
- Target audience: ${params.targetAudience}

## OUTPUT FORMAT
Return a JSON object with:
{
  "slides": [
    { "type": "title|learning-objectives|core-concept|application|summary-proof", "heading": "...", "content": ["bullet1", "bullet2"], "sourceReference": "Chapter 1, Section 2" }
  ]
}`;

    const userPrompt = `Generate a learning deck for the book "${bookTitle}".

Scope: ${params.scope}
${params.chapterNumbers ? `Chapters: ${params.chapterNumbers.join(', ')}` : 'All chapters'}
Target Audience: ${params.targetAudience}
Tone: ${params.tone}
Max Slides: ${params.maxSlides}
Include Visuals: ${params.includeVisuals}

Create a structured, presentation-ready learning deck that proves verified reading and understanding.

Return ONLY valid JSON.`;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.7,
        max_tokens: 4000,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(JSON.stringify({ error: "Rate limits exceeded, please try again later." }), {
          status: 429,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      if (response.status === 402) {
        return new Response(JSON.stringify({ error: "Payment required, please add funds to your workspace." }), {
          status: 402,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      throw new Error(`AI gateway error: ${response.status}`);
    }

    const aiResponse = await response.json();
    const content = aiResponse.choices?.[0]?.message?.content || "";

    // Parse JSON from response
    let slides: SlideData[] = [];
    try {
      // Try to extract JSON from the response
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        slides = parsed.slides || [];
      }
    } catch (parseError) {
      console.error("Failed to parse AI response:", parseError);
      // Create fallback slides
      slides = [
        {
          type: "title",
          heading: bookTitle,
          content: ["Verified Learning Deck", "Generated by ScrollLibrary"],
        },
        {
          type: "summary-proof",
          heading: "Summary",
          content: ["Deck generation requires valid content response.", "Please try again."],
        },
      ];
    }

    // Build the deck object
    const deck = {
      id: crypto.randomUUID(),
      title: `${bookTitle} - Learning Deck`,
      slides,
      metadata: {
        bookId: params.certificationContext.bookId,
        bookVersion: params.certificationContext.bookVersion,
        contentHash: params.certificationContext.contentHash,
        chaptersCovered: params.chapterNumbers || [],
        generatedAt: new Date().toISOString(),
        generatedAfterAssessment: true,
        scope: params.scope,
        targetAudience: params.targetAudience,
        tone: params.tone,
      },
      isValid: true,
      eligibility: {
        isEligible: true,
        chaptersRead: params.chapterNumbers || [],
        chaptersRequired: params.chapterNumbers || [],
        quizzesAttempted: params.chapterNumbers || [],
        quizzesRequired: params.chapterNumbers || [],
        readProgress: 100,
        hasIntegrityFlags: false,
      },
    };

    return new Response(JSON.stringify({ deck }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error("Learning deck generation error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Generation failed" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
