import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import {
  BarChart3, BookOpen, CalendarDays, CheckCircle2, ClipboardCheck, Download,
  GraduationCap, Layers3, RefreshCcw, School, Settings2, Target, Upload, UserCog, Users,
} from 'lucide-react';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { useToast } from '@/hooks/use-toast';
import { useUniversity } from '@/hooks/useUniversity';
import { useUniversityOperations } from '@/hooks/useUniversityOperations';
import { useSubscription } from '@/contexts/SubscriptionContext';
import { downloadCsv, formatUniversityRole, parseUniversityRosterCsv } from '@/lib/university';

const fieldClass = 'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';

function Metric({ label, value, note }: { label: string; value: number | string; note?: string }) {
  return <Card><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="text-3xl font-bold mt-1">{value}</p>{note && <p className="text-xs text-muted-foreground mt-1">{note}</p>}</CardContent></Card>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>;
}

function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <Card><CardHeader><CardTitle>{title}</CardTitle>{description && <CardDescription>{description}</CardDescription>}</CardHeader><CardContent>{children}</CardContent></Card>;
}

function Empty({ children }: { children: React.ReactNode }) {
  return <p className="text-sm text-muted-foreground py-6 text-center">{children}</p>;
}

export default function UniversityHub() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { user } = useSubscription();
  const university = useUniversity();
  const ops = useUniversityOperations(university.activeOrgId, university.refresh);
  const {
    activeOrg, activeOrgId, settingsExists, people, programmes, courses, terms, cohorts, offerings,
    teachingAssignments, enrolments, assignments, gradeItems, transcript, outcomes, modules, announcements,
    loading, error, universityRole, isAcademicAdmin, isStaff, isStudent, courseById, termById,
    offeringById, personByUserId, initializeUniversity, insert, update, provisionRoster, saveGrade, refresh,
  } = university;

  const [busy, setBusy] = useState(false);
  const [programme, setProgramme] = useState({ code: '', name: '', qualification_level: 'bachelor', total_credits: '120' });
  const [course, setCourse] = useState({ code: '', title: '', credits: '5', level: '1', delivery_mode: 'online' });
  const [term, setTerm] = useState({ code: '', name: '', academic_year: '', starts_on: '', ends_on: '' });
  const [cohort, setCohort] = useState({ code: '', name: '', programme_id: '', intake_year: String(new Date().getFullYear()) });
  const [offering, setOffering] = useState({ course_id: '', term_id: '', cohort_id: '', section_code: 'A', capacity: '100' });
  const [curriculum, setCurriculum] = useState({ programme_id: '', course_id: '', year_number: '1', term_number: '1', sequence: '1' });
  const [prerequisite, setPrerequisite] = useState({ course_id: '', prerequisite_course_id: '', minimum_grade: '50' });
  const [outcome, setOutcome] = useState({ scope: 'course', parent_id: '', code: '', description: '', bloom_level: 'apply' });
  const [moduleForm, setModuleForm] = useState({ course_id: '', code: '', title: '', sequence: '1', estimated_learning_hours: '2' });
  const [teacher, setTeacher] = useState({ offering_id: '', user_id: '', teaching_role: 'lecturer' });
  const [enrolment, setEnrolment] = useState({ offering_id: '', user_id: '' });
  const [cohortMember, setCohortMember] = useState({ cohort_id: '', user_id: '' });
  const [assignment, setAssignment] = useState({ offering_id: '', title: '', assignment_type: 'assignment', instructions: '', due_at: '', max_points: '100' });
  const [gradeItem, setGradeItem] = useState({ offering_id: '', name: '', category: 'coursework', max_points: '100', weight_percent: '20' });
  const [selectedGradeItem, setSelectedGradeItem] = useState('');
  const [gradeDrafts, setGradeDrafts] = useState<Record<string, string>>({});
  const [attendance, setAttendance] = useState({ offering_id: '', title: '', starts_at: '', ends_at: '', location: '' });
  const [selectedSession, setSelectedSession] = useState('');
  const [rosterText, setRosterText] = useState('email,display_name,role,student_number,staff_number\n');
  const [submissionDrafts, setSubmissionDrafts] = useState<Record<string, string>>({});
  const [institution, setInstitution] = useState({ timezone: '', locale: '', academic_year_start_month: '9', public_catalog_enabled: false, lms_interop_enabled: false });

  const run = async (work: () => Promise<unknown>, success: string) => {
    setBusy(true);
    try {
      await work();
      toast({ title: success });
    } catch (err) {
      toast({ title: 'University operation failed', description: err instanceof Error ? err.message : String(err), variant: 'destructive' });
    } finally {
      setBusy(false);
    }
  };

  const students = useMemo(() => people.filter((p) => p.university_role === 'student' && p.status !== 'inactive'), [people]);
  const staff = useMemo(() => people.filter((p) => p.university_role !== 'student' && p.status !== 'inactive'), [people]);
  const myTeachingIds = useMemo(() => new Set(teachingAssignments.filter((a) => a.user_id === user?.id).map((a) => a.offering_id)), [teachingAssignments, user?.id]);
  const myEnrolments = useMemo(() => enrolments.filter((e) => e.user_id === user?.id), [enrolments, user?.id]);
  const myOfferingIds = useMemo(() => new Set(myEnrolments.map((e) => e.offering_id)), [myEnrolments]);
  const managedOfferings = isAcademicAdmin ? offerings : offerings.filter((o) => myTeachingIds.has(o.id));
  const studentAssignments = assignments.filter((a) => myOfferingIds.has(a.offering_id));
  const selectedItem = gradeItems.find((g) => g.id === selectedGradeItem) || null;
  const selectedItemEnrolments = selectedItem ? enrolments.filter((e) => e.offering_id === selectedItem.offering_id && ['enrolled', 'completed'].includes(e.status)) : [];
  const selectedSessionRow = ops.attendanceSessions.find((s) => s.id === selectedSession) || null;
  const selectedSessionEnrolments = selectedSessionRow ? enrolments.filter((e) => e.offering_id === selectedSessionRow.offering_id && ['enrolled', 'completed'].includes(e.status)) : [];
  const myProgress = ops.learnerProgress.filter((row) => row.user_id === user?.id);

  if (!activeOrgId || !activeOrg) {
    return <><Navbar /><main className="container mx-auto max-w-3xl px-4 pt-24 pb-16"><Section title="Select an institution" description="ScrollUniversity lives inside an organization so academic records remain tenant-isolated."><Button onClick={() => navigate('/organizations')}><School className="h-4 w-4 mr-2" />Manage organizations</Button></Section></main><Footer /></>;
  }

  if (loading) return <><Navbar /><main className="container mx-auto px-4 pt-24 pb-16">Loading ScrollUniversity…</main><Footer /></>;

  if (!settingsExists) {
    return <><Navbar /><main className="container mx-auto max-w-3xl px-4 pt-24 pb-16"><Section title={`Enable ScrollUniversity for ${activeOrg.name}`} description="This creates the university identity for the organization without changing its existing library data.">{error && <Alert variant="destructive" className="mb-4"><AlertTitle>Schema unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<Button disabled={busy} onClick={() => void run(initializeUniversity, 'ScrollUniversity enabled')}>Enable ScrollUniversity</Button></Section></main><Footer /></>;
  }

  const roleLabel = universityRole ? formatUniversityRole(universityRole) : formatUniversityRole(university.activeRole || 'member');

  const renderOfferingLabel = (offeringId: string) => {
    const o = offeringById.get(offeringId);
    const c = o ? courseById.get(o.course_id) : null;
    const t = o ? termById.get(o.term_id) : null;
    return o ? `${c?.code || 'Course'} · ${t?.name || 'Term'} · ${o.section_code}` : 'Unknown offering';
  };

  const importRoster = async () => {
    const parsed = parseUniversityRosterCsv(rosterText);
    if (parsed.errors.length) throw new Error(parsed.errors.join(' '));
    return provisionRoster(parsed.rows.map((row) => ({
      email: row.email,
      display_name: row.displayName,
      role: row.role,
      student_number: row.studentNumber,
      staff_number: row.staffNumber,
    })));
  };

  const exportProgress = () => downloadCsv(`${activeOrg.slug || 'university'}-learner-progress.csv`, ops.learnerProgress.map((r) => ({
    student_number: r.student_number || '', student_name: r.display_name || '', course_code: r.course_code,
    course_title: r.course_title, term: r.term_name, percentage: r.current_percentage ?? '', attendance: r.attendance_percentage ?? '',
    submitted: r.assignments_submitted, assignments: r.assignments_total, outstanding: r.assignments_outstanding, status: r.enrolment_status,
  })));

  return <><Navbar /><main className="container mx-auto max-w-7xl px-4 pt-24 pb-16">
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between mb-6">
      <div><div className="flex items-center gap-2"><GraduationCap className="h-8 w-8 text-primary" /><h1 className="text-3xl font-bold">ScrollUniversity</h1></div><p className="text-muted-foreground mt-1">{activeOrg.name} · curriculum, delivery, assessment, records and learner success.</p></div>
      <div className="flex gap-2 items-center"><Badge>{roleLabel}</Badge><Button variant="outline" size="sm" onClick={() => void Promise.all([refresh(), ops.refresh()])}><RefreshCcw className="h-4 w-4 mr-1" />Refresh</Button></div>
    </div>

    {(error || ops.error) && <Alert variant="destructive" className="mb-6"><AlertTitle>Some university data could not load</AlertTitle><AlertDescription>{error || ops.error}</AlertDescription></Alert>}

    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
      <Metric label="Students" value={students.length} note={`${staff.length} staff`} />
      <Metric label="Courses" value={courses.length} note={`${offerings.length} live/planned offerings`} />
      <Metric label="Assignments" value={assignments.length} note={`${ops.submissions.length} submissions visible`} />
      <Metric label="Learning outcomes" value={outcomes.length} note={`${modules.length} modules`} />
    </div>

    {isStudent && !isStaff ? (
      <Tabs defaultValue="home" className="space-y-6">
        <TabsList className="flex flex-wrap h-auto"><TabsTrigger value="home">Home</TabsTrigger><TabsTrigger value="coursework">Coursework</TabsTrigger><TabsTrigger value="results">Results</TabsTrigger><TabsTrigger value="attendance">Attendance</TabsTrigger><TabsTrigger value="announcements">Announcements</TabsTrigger></TabsList>
        <TabsContent value="home" className="grid md:grid-cols-2 gap-4">
          <Section title="My courses" description="Current institutional enrolments.">{myEnrolments.length ? <div className="space-y-3">{myEnrolments.map((e) => <div key={e.id} className="border rounded-lg p-3"><p className="font-medium">{renderOfferingLabel(e.offering_id)}</p><div className="flex gap-2 mt-2"><Badge variant="outline">{e.status}</Badge><Button asChild size="sm" variant="outline"><Link to="/library"><BookOpen className="h-4 w-4 mr-1" />Library</Link></Button><Button asChild size="sm" variant="outline"><Link to="/dashboard/mastery"><BarChart3 className="h-4 w-4 mr-1" />Mastery</Link></Button></div></div>)}</div> : <Empty>No active course enrolments.</Empty>}</Section>
          <Section title="Progress snapshot" description="Grades, attendance and outstanding work from institutional records.">{myProgress.length ? <div className="space-y-3">{myProgress.map((r) => <div key={r.offering_id} className="border rounded-lg p-3"><p className="font-medium">{r.course_code} — {r.course_title}</p><div className="grid grid-cols-3 gap-2 text-sm mt-2"><div><span className="text-muted-foreground">Grade</span><br/>{r.current_percentage ?? '—'}%</div><div><span className="text-muted-foreground">Attendance</span><br/>{r.attendance_percentage ?? '—'}%</div><div><span className="text-muted-foreground">Outstanding</span><br/>{r.assignments_outstanding}</div></div></div>)}</div> : <Empty>No progress records yet.</Empty>}</Section>
        </TabsContent>
        <TabsContent value="coursework"><Section title="Assignments and submissions" description="Draft work remains private until submitted.">{studentAssignments.length ? <div className="space-y-5">{studentAssignments.map((a) => { const current = ops.submissions.find((s) => s.assignment_id === a.id && s.user_id === user?.id); return <div key={a.id} className="border rounded-lg p-4"><div className="flex justify-between gap-4"><div><p className="font-semibold">{a.title}</p><p className="text-xs text-muted-foreground">{renderOfferingLabel(a.offering_id)} · {a.assignment_type}</p></div><Badge variant="outline">{current?.status || 'not started'}</Badge></div><p className="text-sm whitespace-pre-wrap mt-3">{(a as any).instructions || ''}</p><Textarea className="mt-3 min-h-32" value={submissionDrafts[a.id] ?? current?.body ?? ''} onChange={(e) => setSubmissionDrafts({ ...submissionDrafts, [a.id]: e.target.value })} placeholder="Write your submission…"/><div className="flex gap-2 mt-3"><Button variant="outline" disabled={busy || ['submitted','late','graded'].includes(current?.status || '')} onClick={() => void run(() => ops.saveSubmission(a.id, submissionDrafts[a.id] ?? current?.body ?? '', false, a.due_at), 'Draft saved')}>Save draft</Button><Button disabled={busy || ['submitted','late','graded'].includes(current?.status || '')} onClick={() => void run(() => ops.saveSubmission(a.id, submissionDrafts[a.id] ?? current?.body ?? '', true, a.due_at), 'Assignment submitted')}>Submit</Button><span className="text-xs text-muted-foreground self-center">{a.due_at ? `Due ${new Date(a.due_at).toLocaleString()}` : 'No deadline'}</span></div></div>; })}</div> : <Empty>No published assignments.</Empty>}</Section></TabsContent>
        <TabsContent value="results"><Section title="Transcript"><div className="flex justify-end mb-3"><Button variant="outline" size="sm" onClick={() => downloadCsv(`${activeOrg.slug || 'university'}-transcript.csv`, transcript as unknown as Array<Record<string, unknown>>)}><Download className="h-4 w-4 mr-1" />CSV</Button></div>{transcript.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Course</th><th>Term</th><th>%</th><th>Grade</th><th>Credits</th><th>Status</th></tr></thead><tbody>{transcript.map((r) => <tr key={`${r.offering_id}-${r.user_id}`} className="border-b"><td className="py-2">{r.course_code} — {r.course_title}</td><td>{r.term_name}</td><td>{r.final_percentage ?? '—'}</td><td>{r.final_grade || '—'}</td><td>{r.credits_earned ?? '—'}</td><td>{r.enrolment_status}</td></tr>)}</tbody></table></div> : <Empty>No transcript records yet.</Empty>}</Section></TabsContent>
        <TabsContent value="attendance"><Section title="My attendance">{ops.attendanceSummary.filter((r) => r.user_id === user?.id).length ? <div className="space-y-3">{ops.attendanceSummary.filter((r) => r.user_id === user?.id).map((r) => <div key={r.offering_id} className="border rounded-lg p-3"><p className="font-medium">{renderOfferingLabel(r.offering_id)}</p><p className="text-sm mt-1">{r.sessions_attended}/{r.sessions_total} attended · {r.sessions_absent} absent · {r.attendance_percentage ?? '—'}%</p></div>)}</div> : <Empty>No attendance has been recorded.</Empty>}</Section></TabsContent>
        <TabsContent value="announcements"><Section title="Announcements">{announcements.length ? <div className="space-y-3">{announcements.map((a) => <div key={a.id} className="border rounded-lg p-3"><p className="font-semibold">{a.title}</p><p className="text-sm whitespace-pre-wrap mt-1">{a.body}</p></div>)}</div> : <Empty>No announcements.</Empty>}</Section></TabsContent>
      </Tabs>
    ) : (
      <Tabs defaultValue="overview" className="space-y-6">
        <TabsList className="flex flex-wrap h-auto"><TabsTrigger value="overview">Overview</TabsTrigger>{isAcademicAdmin && <><TabsTrigger value="academic">Academic</TabsTrigger><TabsTrigger value="delivery">Delivery</TabsTrigger><TabsTrigger value="people">People</TabsTrigger></>}<TabsTrigger value="assessment">Assessment</TabsTrigger><TabsTrigger value="attendance">Attendance</TabsTrigger><TabsTrigger value="analytics">Analytics</TabsTrigger>{isAcademicAdmin && <TabsTrigger value="settings">Settings</TabsTrigger>}</TabsList>

        <TabsContent value="overview" className="grid md:grid-cols-2 gap-4">
          <Section title="Teaching portfolio" description="Offerings you can manage.">{managedOfferings.length ? <div className="space-y-2">{managedOfferings.map((o) => <div key={o.id} className="border rounded-lg p-3"><p className="font-medium">{renderOfferingLabel(o.id)}</p><p className="text-xs text-muted-foreground">Capacity {o.capacity ?? 'unlimited'} · {enrolments.filter((e) => e.offering_id === o.id && e.status === 'enrolled').length} enrolled</p></div>)}</div> : <Empty>No assigned offerings.</Empty>}</Section>
          <Section title="Institution health" description="Operational signals requiring attention."><div className="space-y-2 text-sm"><p>{ops.learnerProgress.filter((r) => r.assignments_outstanding > 0).length} learner-course records have outstanding assignments.</p><p>{ops.learnerProgress.filter((r) => r.attendance_percentage !== null && r.attendance_percentage < 75).length} learner-course records are below 75% attendance.</p><p>{ops.submissions.filter((s) => ['submitted','late'].includes(s.status)).length} submissions await grading.</p><Button asChild variant="outline"><Link to="/dashboard/mastery"><BarChart3 className="h-4 w-4 mr-1" />Open ScrollMastery</Link></Button></div></Section>
        </TabsContent>

        {isAcademicAdmin && <TabsContent value="academic" className="space-y-6">
          <div className="grid lg:grid-cols-2 gap-4">
            <Section title="Programme"><div className="space-y-3"><Field label="Code"><Input value={programme.code} onChange={(e) => setProgramme({ ...programme, code: e.target.value })}/></Field><Field label="Name"><Input value={programme.name} onChange={(e) => setProgramme({ ...programme, name: e.target.value })}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Qualification"><select className={fieldClass} value={programme.qualification_level} onChange={(e) => setProgramme({ ...programme, qualification_level: e.target.value })}><option value="bachelor">Bachelor</option><option value="master">Master</option><option value="doctorate">Doctorate</option><option value="diploma">Diploma</option><option value="certificate">Certificate</option></select></Field><Field label="Credits"><Input type="number" value={programme.total_credits} onChange={(e) => setProgramme({ ...programme, total_credits: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_programmes', { ...programme, total_credits: Number(programme.total_credits), status: 'active' }), 'Programme created')}>Create programme</Button></div></Section>
            <Section title="Course"><div className="space-y-3"><Field label="Code"><Input value={course.code} onChange={(e) => setCourse({ ...course, code: e.target.value })}/></Field><Field label="Title"><Input value={course.title} onChange={(e) => setCourse({ ...course, title: e.target.value })}/></Field><div className="grid grid-cols-3 gap-3"><Field label="Credits"><Input type="number" value={course.credits} onChange={(e) => setCourse({ ...course, credits: e.target.value })}/></Field><Field label="Level"><Input type="number" value={course.level} onChange={(e) => setCourse({ ...course, level: e.target.value })}/></Field><Field label="Delivery"><select className={fieldClass} value={course.delivery_mode} onChange={(e) => setCourse({ ...course, delivery_mode: e.target.value })}><option value="online">Online</option><option value="in_person">In person</option><option value="hybrid">Hybrid</option><option value="self_paced">Self-paced</option></select></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_courses', { ...course, credits: Number(course.credits), level: Number(course.level), status: 'active' }), 'Course created')}>Create course</Button></div></Section>
            <Section title="Academic term"><div className="space-y-3"><div className="grid grid-cols-2 gap-3"><Field label="Code"><Input value={term.code} onChange={(e) => setTerm({ ...term, code: e.target.value })}/></Field><Field label="Academic year"><Input value={term.academic_year} onChange={(e) => setTerm({ ...term, academic_year: e.target.value })}/></Field></div><Field label="Name"><Input value={term.name} onChange={(e) => setTerm({ ...term, name: e.target.value })}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Starts"><Input type="date" value={term.starts_on} onChange={(e) => setTerm({ ...term, starts_on: e.target.value })}/></Field><Field label="Ends"><Input type="date" value={term.ends_on} onChange={(e) => setTerm({ ...term, ends_on: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_academic_terms', { ...term, term_number: 1, status: 'planned' }), 'Academic term created')}>Create term</Button></div></Section>
            <Section title="Cohort"><div className="space-y-3"><Field label="Programme"><select className={fieldClass} value={cohort.programme_id} onChange={(e) => setCohort({ ...cohort, programme_id: e.target.value })}><option value="">Optional</option>{programmes.map((p) => <option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Code"><Input value={cohort.code} onChange={(e) => setCohort({ ...cohort, code: e.target.value })}/></Field><Field label="Intake year"><Input type="number" value={cohort.intake_year} onChange={(e) => setCohort({ ...cohort, intake_year: e.target.value })}/></Field></div><Field label="Name"><Input value={cohort.name} onChange={(e) => setCohort({ ...cohort, name: e.target.value })}/></Field><Button disabled={busy} onClick={() => void run(() => insert('university_cohorts', { ...cohort, programme_id: cohort.programme_id || null, intake_year: Number(cohort.intake_year), status: 'active' }), 'Cohort created')}>Create cohort</Button></div></Section>
            <Section title="Course offering"><div className="space-y-3"><Field label="Course"><select className={fieldClass} value={offering.course_id} onChange={(e) => setOffering({ ...offering, course_id: e.target.value })}><option value="">Select…</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code} — {c.title}</option>)}</select></Field><Field label="Term"><select className={fieldClass} value={offering.term_id} onChange={(e) => setOffering({ ...offering, term_id: e.target.value })}><option value="">Select…</option>{terms.map((t) => <option key={t.id} value={t.id}>{t.code} — {t.name}</option>)}</select></Field><Field label="Cohort"><select className={fieldClass} value={offering.cohort_id} onChange={(e) => setOffering({ ...offering, cohort_id: e.target.value })}><option value="">None</option>{cohorts.map((c) => <option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Section"><Input value={offering.section_code} onChange={(e) => setOffering({ ...offering, section_code: e.target.value })}/></Field><Field label="Capacity"><Input type="number" value={offering.capacity} onChange={(e) => setOffering({ ...offering, capacity: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_course_offerings', { ...offering, cohort_id: offering.cohort_id || null, capacity: Number(offering.capacity), enrolment_status: 'open' }), 'Course offering created')}>Create offering</Button></div></Section>
            <Section title="Curriculum mapping"><div className="space-y-3"><Field label="Programme"><select className={fieldClass} value={curriculum.programme_id} onChange={(e) => setCurriculum({ ...curriculum, programme_id: e.target.value })}><option value="">Select…</option>{programmes.map((p) => <option key={p.id} value={p.id}>{p.code}</option>)}</select></Field><Field label="Course"><select className={fieldClass} value={curriculum.course_id} onChange={(e) => setCurriculum({ ...curriculum, course_id: e.target.value })}><option value="">Select…</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></Field><div className="grid grid-cols-3 gap-3"><Field label="Year"><Input type="number" value={curriculum.year_number} onChange={(e) => setCurriculum({ ...curriculum, year_number: e.target.value })}/></Field><Field label="Term"><Input type="number" value={curriculum.term_number} onChange={(e) => setCurriculum({ ...curriculum, term_number: e.target.value })}/></Field><Field label="Sequence"><Input type="number" value={curriculum.sequence} onChange={(e) => setCurriculum({ ...curriculum, sequence: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_programme_courses', { programme_id: curriculum.programme_id, course_id: curriculum.course_id, year_number: Number(curriculum.year_number), term_number: Number(curriculum.term_number), sequence: Number(curriculum.sequence), is_required: true }), 'Course mapped into programme')}>Map course</Button></div></Section>
            <Section title="Prerequisite"><div className="space-y-3"><Field label="Course"><select className={fieldClass} value={prerequisite.course_id} onChange={(e) => setPrerequisite({ ...prerequisite, course_id: e.target.value })}><option value="">Select…</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></Field><Field label="Prerequisite"><select className={fieldClass} value={prerequisite.prerequisite_course_id} onChange={(e) => setPrerequisite({ ...prerequisite, prerequisite_course_id: e.target.value })}><option value="">Select…</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></Field><Field label="Minimum %"><Input type="number" value={prerequisite.minimum_grade} onChange={(e) => setPrerequisite({ ...prerequisite, minimum_grade: e.target.value })}/></Field><Button disabled={busy} onClick={() => void run(() => insert('university_course_prerequisites', { course_id: prerequisite.course_id, prerequisite_course_id: prerequisite.prerequisite_course_id, minimum_grade: Number(prerequisite.minimum_grade) }), 'Prerequisite added')}>Add prerequisite</Button></div></Section>
            <Section title="Learning outcome"><div className="space-y-3"><Field label="Scope"><select className={fieldClass} value={outcome.scope} onChange={(e) => setOutcome({ ...outcome, scope: e.target.value, parent_id: '' })}><option value="course">Course</option><option value="programme">Programme</option></select></Field><Field label={outcome.scope === 'course' ? 'Course' : 'Programme'}><select className={fieldClass} value={outcome.parent_id} onChange={(e) => setOutcome({ ...outcome, parent_id: e.target.value })}><option value="">Select…</option>{(outcome.scope === 'course' ? courses : programmes).map((p: any) => <option key={p.id} value={p.id}>{p.code} — {p.title || p.name}</option>)}</select></Field><Field label="Code"><Input value={outcome.code} onChange={(e) => setOutcome({ ...outcome, code: e.target.value })}/></Field><Field label="Description"><Textarea value={outcome.description} onChange={(e) => setOutcome({ ...outcome, description: e.target.value })}/></Field><Button disabled={busy} onClick={() => void run(() => insert('university_learning_outcomes', { code: outcome.code, description: outcome.description, bloom_level: outcome.bloom_level, course_id: outcome.scope === 'course' ? outcome.parent_id : null, programme_id: outcome.scope === 'programme' ? outcome.parent_id : null }), 'Learning outcome created')}>Create outcome</Button></div></Section>
            <Section title="Course module"><div className="space-y-3"><Field label="Course"><select className={fieldClass} value={moduleForm.course_id} onChange={(e) => setModuleForm({ ...moduleForm, course_id: e.target.value })}><option value="">Select…</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Code"><Input value={moduleForm.code} onChange={(e) => setModuleForm({ ...moduleForm, code: e.target.value })}/></Field><Field label="Sequence"><Input type="number" value={moduleForm.sequence} onChange={(e) => setModuleForm({ ...moduleForm, sequence: e.target.value })}/></Field></div><Field label="Title"><Input value={moduleForm.title} onChange={(e) => setModuleForm({ ...moduleForm, title: e.target.value })}/></Field><Button disabled={busy} onClick={() => void run(() => insert('university_modules', { ...moduleForm, sequence: Number(moduleForm.sequence), estimated_learning_hours: Number(moduleForm.estimated_learning_hours), active: true }), 'Module created')}>Create module</Button></div></Section>
          </div>
        </TabsContent>}

        {isAcademicAdmin && <TabsContent value="delivery" className="space-y-6">
          <div className="grid lg:grid-cols-3 gap-4">
            <Section title="Assign lecturer / TA"><div className="space-y-3"><Field label="Offering"><select className={fieldClass} value={teacher.offering_id} onChange={(e) => setTeacher({ ...teacher, offering_id: e.target.value })}><option value="">Select…</option>{offerings.map((o) => <option key={o.id} value={o.id}>{renderOfferingLabel(o.id)}</option>)}</select></Field><Field label="Staff"><select className={fieldClass} value={teacher.user_id} onChange={(e) => setTeacher({ ...teacher, user_id: e.target.value })}><option value="">Select…</option>{staff.map((p) => <option key={p.user_id} value={p.user_id}>{p.display_name || p.staff_number || p.user_id} · {formatUniversityRole(p.university_role)}</option>)}</select></Field><Field label="Teaching role"><select className={fieldClass} value={teacher.teaching_role} onChange={(e) => setTeacher({ ...teacher, teaching_role: e.target.value })}><option value="lead_lecturer">Lead lecturer</option><option value="lecturer">Lecturer</option><option value="teaching_assistant">Teaching assistant</option><option value="grader">Grader</option><option value="observer">Observer</option></select></Field><Button disabled={busy} onClick={() => void run(() => ops.addTeachingAssignment(teacher.offering_id, teacher.user_id, teacher.teaching_role), 'Teaching assignment saved')}>Assign staff</Button></div></Section>
            <Section title="Enrol student"><div className="space-y-3"><Field label="Offering"><select className={fieldClass} value={enrolment.offering_id} onChange={(e) => setEnrolment({ ...enrolment, offering_id: e.target.value })}><option value="">Select…</option>{offerings.map((o) => <option key={o.id} value={o.id}>{renderOfferingLabel(o.id)}</option>)}</select></Field><Field label="Student"><select className={fieldClass} value={enrolment.user_id} onChange={(e) => setEnrolment({ ...enrolment, user_id: e.target.value })}><option value="">Select…</option>{students.map((p) => <option key={p.user_id} value={p.user_id}>{p.student_number || '—'} · {p.display_name || p.user_id}</option>)}</select></Field><Button disabled={busy} onClick={() => void run(() => ops.enrolLearner(enrolment.offering_id, enrolment.user_id), 'Student enrolled')}>Enrol student</Button></div></Section>
            <Section title="Add to cohort"><div className="space-y-3"><Field label="Cohort"><select className={fieldClass} value={cohortMember.cohort_id} onChange={(e) => setCohortMember({ ...cohortMember, cohort_id: e.target.value })}><option value="">Select…</option>{cohorts.map((c) => <option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select></Field><Field label="Student"><select className={fieldClass} value={cohortMember.user_id} onChange={(e) => setCohortMember({ ...cohortMember, user_id: e.target.value })}><option value="">Select…</option>{students.map((p) => <option key={p.user_id} value={p.user_id}>{p.student_number || '—'} · {p.display_name || p.user_id}</option>)}</select></Field><Button disabled={busy} onClick={() => void run(() => ops.addCohortMember(cohortMember.cohort_id, cohortMember.user_id), 'Student added to cohort')}>Add to cohort</Button></div></Section>
          </div>
          <Section title="Current teaching assignments">{teachingAssignments.length ? <div className="space-y-2">{teachingAssignments.map((a) => <div key={a.id} className="border rounded-lg p-3 flex items-center justify-between gap-3"><div><p className="font-medium">{renderOfferingLabel(a.offering_id)}</p><p className="text-xs text-muted-foreground">{personByUserId.get(a.user_id)?.display_name || a.user_id} · {formatUniversityRole(a.teaching_role)}</p></div><Button size="sm" variant="outline" onClick={() => void run(() => ops.removeTeachingAssignment(a.id), 'Teaching assignment removed')}>Remove</Button></div>)}</div> : <Empty>No teaching assignments.</Empty>}</Section>
          <Section title="Enrolment register">{enrolments.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Student</th><th>Offering</th><th>Status</th><th>Final %</th><th></th></tr></thead><tbody>{enrolments.map((e) => <tr key={e.id} className="border-b"><td className="py-2">{personByUserId.get(e.user_id)?.display_name || e.user_id}</td><td>{renderOfferingLabel(e.offering_id)}</td><td><Badge variant="outline">{e.status}</Badge></td><td>{e.final_percentage ?? '—'}</td><td>{['enrolled','completed'].includes(e.status) && <Button size="sm" variant="outline" onClick={() => void run(() => ops.finalizeEnrolment(e.id), 'Course result finalized')}>Finalize</Button>}</td></tr>)}</tbody></table></div> : <Empty>No enrolments.</Empty>}</Section>
        </TabsContent>}

        {isAcademicAdmin && <TabsContent value="people" className="space-y-6">
          <Section title="Bulk provisioning" description="CSV columns: email, display_name, role, student_number, staff_number. Up to 500 people per request."><Textarea className="min-h-48 font-mono text-xs" value={rosterText} onChange={(e) => setRosterText(e.target.value)}/><Button className="mt-3" disabled={busy} onClick={() => void run(importRoster, 'Roster processed')}><Upload className="h-4 w-4 mr-1" />Provision roster</Button></Section>
          <Section title="Institution directory">{people.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Name</th><th>Role</th><th>Student #</th><th>Staff #</th><th>Status</th></tr></thead><tbody>{people.map((p) => <tr key={p.id} className="border-b"><td className="py-2">{p.display_name || '—'}</td><td>{formatUniversityRole(p.university_role)}</td><td>{p.student_number || '—'}</td><td>{p.staff_number || '—'}</td><td><Badge variant="outline">{p.status}</Badge></td></tr>)}</tbody></table></div> : <Empty>No university people.</Empty>}</Section>
        </TabsContent>}

        <TabsContent value="assessment" className="space-y-6">
          <div className="grid lg:grid-cols-2 gap-4">
            <Section title="Create assignment"><div className="space-y-3"><Field label="Offering"><select className={fieldClass} value={assignment.offering_id} onChange={(e) => setAssignment({ ...assignment, offering_id: e.target.value })}><option value="">Select…</option>{managedOfferings.map((o) => <option key={o.id} value={o.id}>{renderOfferingLabel(o.id)}</option>)}</select></Field><Field label="Title"><Input value={assignment.title} onChange={(e) => setAssignment({ ...assignment, title: e.target.value })}/></Field><Field label="Type"><select className={fieldClass} value={assignment.assignment_type} onChange={(e) => setAssignment({ ...assignment, assignment_type: e.target.value })}><option value="assignment">Assignment</option><option value="quiz">Quiz</option><option value="exam">Exam</option><option value="essay">Essay</option><option value="project">Project</option><option value="lab">Lab</option><option value="presentation">Presentation</option><option value="mastery_check">Mastery check</option></select></Field><Field label="Instructions"><Textarea value={assignment.instructions} onChange={(e) => setAssignment({ ...assignment, instructions: e.target.value })}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Due"><Input type="datetime-local" value={assignment.due_at} onChange={(e) => setAssignment({ ...assignment, due_at: e.target.value })}/></Field><Field label="Points"><Input type="number" value={assignment.max_points} onChange={(e) => setAssignment({ ...assignment, max_points: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_assignments', { offering_id: assignment.offering_id, title: assignment.title, assignment_type: assignment.assignment_type, instructions: assignment.instructions, due_at: assignment.due_at ? new Date(assignment.due_at).toISOString() : null, max_points: Number(assignment.max_points), published: true, created_by: user?.id }), 'Assignment published')}>Publish assignment</Button></div></Section>
            <Section title="Create grade item"><div className="space-y-3"><Field label="Offering"><select className={fieldClass} value={gradeItem.offering_id} onChange={(e) => setGradeItem({ ...gradeItem, offering_id: e.target.value })}><option value="">Select…</option>{managedOfferings.map((o) => <option key={o.id} value={o.id}>{renderOfferingLabel(o.id)}</option>)}</select></Field><Field label="Name"><Input value={gradeItem.name} onChange={(e) => setGradeItem({ ...gradeItem, name: e.target.value })}/></Field><div className="grid grid-cols-3 gap-3"><Field label="Category"><Input value={gradeItem.category} onChange={(e) => setGradeItem({ ...gradeItem, category: e.target.value })}/></Field><Field label="Points"><Input type="number" value={gradeItem.max_points} onChange={(e) => setGradeItem({ ...gradeItem, max_points: e.target.value })}/></Field><Field label="Weight %"><Input type="number" value={gradeItem.weight_percent} onChange={(e) => setGradeItem({ ...gradeItem, weight_percent: e.target.value })}/></Field></div><Button disabled={busy} onClick={() => void run(() => insert('university_grade_items', { ...gradeItem, max_points: Number(gradeItem.max_points), weight_percent: Number(gradeItem.weight_percent), published: true }), 'Grade item created')}>Create grade item</Button></div></Section>
          </div>
          <Section title="Gradebook"><Field label="Grade item"><select className={fieldClass} value={selectedGradeItem} onChange={(e) => setSelectedGradeItem(e.target.value)}><option value="">Select grade item…</option>{gradeItems.filter((g) => managedOfferings.some((o) => o.id === g.offering_id)).map((g) => <option key={g.id} value={g.id}>{renderOfferingLabel(g.offering_id)} · {g.name}</option>)}</select></Field>{selectedItem && <div className="mt-4 space-y-2">{selectedItemEnrolments.map((e) => <div key={e.id} className="grid grid-cols-[1fr_120px_auto] gap-3 items-center border-b py-2"><div>{personByUserId.get(e.user_id)?.display_name || e.user_id}</div><Input type="number" min="0" max="100" value={gradeDrafts[e.user_id] || ''} onChange={(ev) => setGradeDrafts({ ...gradeDrafts, [e.user_id]: ev.target.value })} placeholder="%"/><Button size="sm" disabled={busy} onClick={() => { const value = Number(gradeDrafts[e.user_id]); if (!Number.isFinite(value) || value < 0 || value > 100) { toast({ title: 'Enter 0–100%', variant: 'destructive' }); return; } void run(() => saveGrade(selectedItem, e.user_id, value), 'Grade published'); }}>Save</Button></div>)}</div>}</Section>
          <Section title="Submissions awaiting review">{ops.submissions.filter((s) => ['submitted','late'].includes(s.status)).length ? <div className="space-y-3">{ops.submissions.filter((s) => ['submitted','late'].includes(s.status)).map((s) => { const a = assignments.find((x) => x.id === s.assignment_id); return <div key={s.id} className="border rounded-lg p-3"><div className="flex justify-between"><div><p className="font-medium">{a?.title || s.assignment_id}</p><p className="text-xs text-muted-foreground">{personByUserId.get(s.user_id)?.display_name || s.user_id}</p></div><Badge>{s.status}</Badge></div><p className="text-sm whitespace-pre-wrap mt-3">{s.body || 'No text body.'}</p></div>; })}</div> : <Empty>No submitted work awaiting review.</Empty>}</Section>
        </TabsContent>

        <TabsContent value="attendance" className="space-y-6">
          <Section title="Create attendance session"><div className="grid md:grid-cols-5 gap-3"><Field label="Offering"><select className={fieldClass} value={attendance.offering_id} onChange={(e) => setAttendance({ ...attendance, offering_id: e.target.value })}><option value="">Select…</option>{managedOfferings.map((o) => <option key={o.id} value={o.id}>{renderOfferingLabel(o.id)}</option>)}</select></Field><Field label="Title"><Input value={attendance.title} onChange={(e) => setAttendance({ ...attendance, title: e.target.value })}/></Field><Field label="Starts"><Input type="datetime-local" value={attendance.starts_at} onChange={(e) => setAttendance({ ...attendance, starts_at: e.target.value })}/></Field><Field label="Ends"><Input type="datetime-local" value={attendance.ends_at} onChange={(e) => setAttendance({ ...attendance, ends_at: e.target.value })}/></Field><Field label="Location"><Input value={attendance.location} onChange={(e) => setAttendance({ ...attendance, location: e.target.value })}/></Field></div><Button className="mt-3" disabled={busy} onClick={() => void run(() => ops.createAttendanceSession({ offering_id: attendance.offering_id, title: attendance.title, starts_at: new Date(attendance.starts_at).toISOString(), ends_at: attendance.ends_at ? new Date(attendance.ends_at).toISOString() : null, location: attendance.location || null }), 'Attendance session created')}>Create session</Button></Section>
          <Section title="Record attendance"><Field label="Session"><select className={fieldClass} value={selectedSession} onChange={(e) => setSelectedSession(e.target.value)}><option value="">Select session…</option>{ops.attendanceSessions.filter((s) => managedOfferings.some((o) => o.id === s.offering_id)).map((s) => <option key={s.id} value={s.id}>{s.title} · {renderOfferingLabel(s.offering_id)} · {new Date(s.starts_at).toLocaleString()}</option>)}</select></Field>{selectedSessionRow && <div className="mt-4 space-y-2">{selectedSessionEnrolments.map((e) => { const existing = ops.recordsBySession.get(selectedSessionRow.id)?.find((r) => r.user_id === e.user_id); return <div key={e.id} className="grid grid-cols-[1fr_auto] gap-3 items-center border-b py-2"><div>{personByUserId.get(e.user_id)?.display_name || e.user_id}<span className="text-xs text-muted-foreground ml-2">{existing?.status || 'unmarked'}</span></div><div className="flex flex-wrap gap-1">{(['present','late','remote','absent','excused'] as const).map((status) => <Button key={status} size="sm" variant={existing?.status === status ? 'default' : 'outline'} onClick={() => void run(() => ops.recordAttendance(selectedSessionRow.id, e.user_id, status), `Marked ${status}`)}>{status}</Button>)}</div></div>; })}</div>}</Section>
        </TabsContent>

        <TabsContent value="analytics" className="space-y-6">
          <Section title="Learner progress" description="Institutional grades, submissions and attendance combined under RLS."><div className="flex justify-end mb-3"><Button variant="outline" size="sm" onClick={exportProgress}><Download className="h-4 w-4 mr-1" />Export CSV</Button></div>{ops.learnerProgress.length ? <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Learner</th><th>Course</th><th>%</th><th>Attendance</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{ops.learnerProgress.map((r) => <tr key={`${r.offering_id}-${r.user_id}`} className="border-b"><td className="py-2">{r.student_number || '—'} · {r.display_name || r.user_id}</td><td>{r.course_code}</td><td>{r.current_percentage ?? '—'}</td><td>{r.attendance_percentage ?? '—'}%</td><td>{r.assignments_outstanding}</td><td><Badge variant="outline">{r.enrolment_status}</Badge></td></tr>)}</tbody></table></div> : <Empty>No learner progress records.</Empty>}</Section>
        </TabsContent>

        {isAcademicAdmin && <TabsContent value="settings"><Section title="Institution settings" description="Academic calendar, locale and interoperability policy."><div className="grid md:grid-cols-2 gap-4"><Field label="Timezone"><Input value={institution.timezone || ops.settings?.timezone || ''} onChange={(e) => setInstitution({ ...institution, timezone: e.target.value })}/></Field><Field label="Locale"><Input value={institution.locale || ops.settings?.locale || ''} onChange={(e) => setInstitution({ ...institution, locale: e.target.value })}/></Field><Field label="Academic year start month"><Input type="number" min="1" max="12" value={institution.academic_year_start_month} onChange={(e) => setInstitution({ ...institution, academic_year_start_month: e.target.value })}/></Field><div className="space-y-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={institution.public_catalog_enabled || ops.settings?.public_catalog_enabled || false} onChange={(e) => setInstitution({ ...institution, public_catalog_enabled: e.target.checked })}/> Public course catalogue</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={institution.lms_interop_enabled || ops.settings?.lms_interop_enabled || false} onChange={(e) => setInstitution({ ...institution, lms_interop_enabled: e.target.checked })}/> LMS interoperability enabled</label></div></div><Button className="mt-4" disabled={busy} onClick={() => void run(() => ops.saveSettings({ timezone: institution.timezone || ops.settings?.timezone || 'UTC', locale: institution.locale || ops.settings?.locale || 'en', academic_year_start_month: Number(institution.academic_year_start_month), public_catalog_enabled: institution.public_catalog_enabled || ops.settings?.public_catalog_enabled || false, lms_interop_enabled: institution.lms_interop_enabled || ops.settings?.lms_interop_enabled || false }), 'Institution settings saved')}><Settings2 className="h-4 w-4 mr-1" />Save settings</Button></Section></TabsContent>}
      </Tabs>
    )}
  </main><Footer /></>;
}
